-- Create tables for raw data to be loaded into
CREATE TABLE weather (
	DATE DATE PRIMARY KEY,
	STATION VARCHAR(30),
	NAME VARCHAR(75),
	TMAX FLOAT,
	TMIN FLOAT,
	TOBS FLOAT
);
CREATE TABLE wti (
	DATE DATE PRIMARY KEY,
	"Daily Crude Oil Price" FLOAT
);
CREATE TABLE kwh (
	DATE DATE PRIMARY KEY,
	"$/KWH" FLOAT
);