CREATE TABLE "STATS"(
	REGION VARCHAR,
	COUNTRY VARCHAR,
	ISO_CODE VARCHAR,
	RENON_RE VARCHAR,
	GROUP_TECHNOLOGY VARCHAR,
	TECHNOLOGY VARCHAR,
	PRODUCER_TYPE VARCHAR,
	YEAR INT,
	ELECTRICITY_INSTALLED INT
)

-- DROP TABLE IF EXISTS "STATS"

SELECT * FROM "STATS"